"""Paper-extension mode — the direct Madan & Pearce (2025) comparison layer only.

Runs, for the 18 amino acids, the *exact* paper fiducial: C2H2/HCN = 2.1
(C2H2 0.042 / HCN 0.020) at:
  - NH3 excluded (the "0% NH3" point), and
  - NH3 = [0.01, 0.02, 0.03, 0.04, 0.05, 0.10] (1%..10% of water).
Then writes studies/_paper_extension/paper_extension_metrics.csv (one row per amino
acid, yield % relative to initial HCN) + summary.md. This isolates "paper
reproduction/extension" from the broad sensitivity discovery; it reuses the engine
and adds no new physics.

Usage:
    R_HOME=$(R RHOME) python scripts/run_paper_extension.py
    python scripts/run_paper_extension.py --only glycine,proline
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from sensitivity_compare import assemble_bridge_table, load_campaign  # noqa: E402
import new_amino_acid_batch as scaffold  # noqa: E402
import run_sensitivity_study  # noqa: E402
import summarize_sensitivity_study  # noqa: E402

OUT = "studies/_paper_extension"
RATIO = 2.1
NH3_SERIES = [0.01, 0.02, 0.03, 0.04, 0.05, 0.10]
HEADER = "# Paper-extension fiducial (auto-generated by scripts/run_paper_extension.py).\n"


def _fiducialize(config_path: Path, batch: str) -> None:
    """Pin the inventory sweep to the exact paper fiducial (ratio 2.1, NH3 series)."""
    cfg = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    inv = cfg["sweeps"]["inventory_landscape"]["variables"]
    inv["C2H2_over_HCN"] = {"type": "explicit", "values": [RATIO]}
    if batch == "B":
        inv["NH3(aq)"] = {"type": "explicit", "values": list(NH3_SERIES)}
    if "nh3_deltaG_landscape" in cfg.get("sweeps", {}):
        cfg["sweeps"]["nh3_deltaG_landscape"]["enabled"] = False   # not needed for the bridge
    config_path.write_text(
        HEADER + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False),
        encoding="utf-8")


def scaffold_fiducial_studies(only=None, force=True):
    a = scaffold.scaffold_studies(scaffold.DEFAULT_SPECIES_CSV, scaffold.DEFAULT_TEMPLATE,
                                  f"{OUT}/aa_no_nh3", only, force, exclude_species=("NH3(aq)",))
    b = scaffold.scaffold_studies(scaffold.DEFAULT_SPECIES_CSV, scaffold.DEFAULT_TEMPLATE,
                                  f"{OUT}/aa_nh3", only, force)
    for p in a["created"]:
        _fiducialize(p, "A")
    for p in b["created"]:
        _fiducialize(p, "B")
    return a["created"], b["created"]


def _run_study(config_path: Path) -> bool:
    rc = run_sensitivity_study.main(["--config", str(config_path)])
    if rc not in (0,):
        return False
    return summarize_sensitivity_study.main(["--config", str(config_path)]) == 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", default=None, help="Comma-separated amino-acid keys.")
    parser.add_argument("--force", action="store_true",
                        help="Re-scaffold/re-run even if outputs exist (default resumes).")
    parser.add_argument("--ratio", type=float, default=RATIO)
    args = parser.parse_args(argv)
    only = [k.strip() for k in args.only.split(",")] if args.only else None

    a_paths, b_paths = scaffold_fiducial_studies(only, force=True)
    print(f"Fiducial studies: {len(a_paths)} no-NH3 + {len(b_paths)} NH3.")

    failures = []
    for p in a_paths + b_paths:
        if not _run_study(p):
            failures.append(p.parent.name)
    if failures:
        print(f"WARNING: studies that did not complete (need a Cantera env?): {sorted(set(failures))}",
              file=sys.stderr)

    camp_a = load_campaign(PROJECT_ROOT / OUT / "aa_no_nh3")
    camp_b = load_campaign(PROJECT_ROOT / OUT / "aa_nh3")
    if not camp_a and not camp_b:
        print("No completed studies — re-run in a Cantera environment.", file=sys.stderr)
        return 1

    table = assemble_bridge_table(camp_a, camp_b, ratio=args.ratio)
    out_dir = PROJECT_ROOT / OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    table.to_csv(out_dir / "paper_extension_metrics.csv", index=False)
    _write_summary(table, out_dir / "summary.md", args.ratio)

    groups = table["paper_group"].value_counts().to_dict()
    print(f"Wrote {out_dir}/paper_extension_metrics.csv ({len(table)} amino acids). "
          f"Groups: {groups}")
    return 0 if not failures else 1


def _write_summary(table, out_path: Path, ratio: float):
    no_nh3 = table[table["accessible_no_nh3"]]["amino_acid"].tolist()
    unlocked = table[table["paper_group"] == "nh3_unlocked"]["amino_acid"].tolist()
    lines = [f"# Paper extension — fiducial C2H2/HCN = {ratio}", "",
             "Direct comparison to Madan & Pearce (2025): which amino acids are "
             "equilibrium-accessible with **no NH3**, and the yield (% of initial HCN) "
             "as NH3 rises from 1% to 10% of water.", "",
             f"## Accessible with NO ammonia ({len(no_nh3)})", ", ".join(no_nh3) or "(none)", "",
             f"## Unlocked only by NH3 ({len(unlocked)})", ", ".join(unlocked) or "(none)", "",
             "## Yield (% of HCN) at the fiducial", "",
             "| amino acid | no NH3 | 1% | 5% | 10% | group |", "|---|---|---|---|---|---|"]
    for _, r in table.iterrows():
        def f(v):
            return "—" if v is None or pd.isna(v) else f"{v:.2g}"
        lines.append(f"| {r['amino_acid']} | {f(r['yield_pct_HCN_no_nh3'])} | "
                     f"{f(r['yield_pct_HCN_1pct'])} | {f(r['yield_pct_HCN_5pct'])} | "
                     f"{f(r['yield_pct_HCN_10pct'])} | {r['paper_group']} |")
    lines += ["", "M&P find only a few amino acids accessible with no ammonia of any "
              "kind; ammonia in the feedstock unlocks the rest — reproduced above as "
              "the equilibrium-accessibility analogue."]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
