"""Run a sensitivity study: build model/run manifests and execute the cases.

Reuses the validated v1.0 engine (``run_single_yaml_case``) and proves model reuse
(an inventory sweep collapses to one Cantera YAML; ΔG offsets add one shared model
per offset). ΔG variant coefficients are generated by an exact analytic a7 shift
(``sensitivity_thermo.shift_coeffs_by_gibbs``) during coefficient prep, so all cases
— inventory and ΔG — run in one pass.

Usage:
    python scripts/run_sensitivity_study.py --config studies/alanine_mvp/study_config.yaml --dry-run
    python scripts/run_sensitivity_study.py --config studies/alanine_mvp/study_config.yaml
    python scripts/run_sensitivity_study.py --config studies/alanine_mvp/study_config.yaml --substudy inventory_landscape
    python scripts/run_sensitivity_study.py --config studies/alanine_mvp/study_config.yaml --only-failed
    python scripts/run_sensitivity_study.py --config studies/alanine_mvp/study_config.yaml --limit 50
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import pandas as pd  # noqa: E402

from config_io import load_scenarios  # noqa: E402
from thermo_fit import fit_all_species, load_coefficients  # noqa: E402
from sensitivity_design import (  # noqa: E402
    StudyConfigError,
    build_full_design_matrix,
    build_thermo_offsets_table,
    load_gibbs_seed_for_config,
    load_species_for_config,
    load_study_config,
    validate_study,
    write_design_outputs,
)
from sensitivity_thermo import (  # noqa: E402
    augment_species_metadata_with_variants,
    require_gibbs_seed,
    shift_coeffs_by_gibbs,
)
from sensitivity_runner import (  # noqa: E402
    add_case_hash,
    build_model_manifest,
    build_run_manifest,
    compute_model_table,
    model_reuse_stats,
    run_sensitivity_manifest,
    select_cases_to_run,
    seed_is_stale,
    write_run_provenance,
)


def _study_dir(config) -> Path:
    return PROJECT_ROOT / config["study"].get(
        "output_dir", f"studies/{config['study']['study_id']}")


def prepare_study_coefficients(config, study_dir: Path, force: bool = False) -> Path:
    """Build the study-local NASA9 coefficients: fit the base species from the seed,
    then append an exact a7-shifted row-pair for every ΔG variant (no refit).

    Reuses the cached file only when it already contains every required variant, so
    enabling a ΔG sweep on an existing study regenerates the variant coefficients.
    """
    coeff_path = study_dir / "processed" / "nasa9_coefficients.csv"
    offsets_df = build_thermo_offsets_table(config)
    required = set(offsets_df["variant_species"]) if not offsets_df.empty else set()
    if coeff_path.exists() and not force:
        existing = load_coefficients(coeff_path)
        if required <= set(existing["cantera_name"]):
            return coeff_path

    seed_rel = require_gibbs_seed(config)
    fit_all_species(
        gibbs_wide_csv=PROJECT_ROOT / seed_rel,
        coefficients_csv=coeff_path,
        diagnostics_csv=study_dir / "processed" / "nasa9_fit_diagnostics.csv",
        make_plots=False,
    )
    if not offsets_df.empty:
        base_coeffs = load_coefficients(coeff_path)
        frames = [base_coeffs]
        for _, off in offsets_df.iterrows():
            frames.append(shift_coeffs_by_gibbs(
                base_coeffs, off["base_species"], off["variant_species"],
                off["deltaG_offset_kJ_mol"]))
        pd.concat(frames, ignore_index=True).to_csv(coeff_path, index=False)
    return coeff_path


def _load_coeff_for_preview(config, study_dir: Path) -> pd.DataFrame:
    """Read-only coefficients for dry-run identity counting (no fitting/writes)."""
    study_coeff = study_dir / "processed" / "nasa9_coefficients.csv"
    if study_coeff.exists():
        return load_coefficients(study_coeff)
    return load_coefficients(PROJECT_ROOT / "data" / "processed" / "nasa9_coefficients.csv")


def _partition_runnable(design_df: pd.DataFrame, coeff_df: pd.DataFrame):
    """Split the design by whether each target variant's coefficients are present.

    ``materialized`` cases have their NASA9 coefficients ready (base + any ΔG
    variants whose a7-shifted rows have been generated). ``unmaterialized`` cases
    are conceptually supported but their coefficients have not been built yet in
    this study directory (running the study materializes them).
    """
    have = set(coeff_df["cantera_name"])
    materialized = design_df[design_df["target_variant"].isin(have)].copy()
    unmaterialized = design_df[~design_df["target_variant"].isin(have)].copy()
    return materialized, unmaterialized


def _print_counts(design_df, runnable, unmaterialized, models_df, reuse):
    print("\nDesign:")
    for sub, n in design_df["substudy_id"].value_counts().items():
        print(f"  - {sub:<22} {n:>6} cases")
    print(f"  {'TOTAL':<22} {len(design_df):>6} cases")
    print(f"\nCurrently materialized: {len(runnable)} runnable, "
          f"{len(unmaterialized)} not yet materialized")
    if len(unmaterialized):
        subs = ", ".join(sorted(unmaterialized['substudy_id'].unique()))
        print(f"  (run the study to build the missing ΔG coefficients: "
              f"{len(unmaterialized)} cases [{subs}])")
    print(f"\nUnique models: {reuse['n_models']}  "
          f"(reuse ratio {reuse['reuse_ratio']:.1f} cases/model)")


def _mode_label(args) -> str:
    if args.force:
        return "force/rerun-all"
    if args.only_failed:
        return "only-failed"
    return "resume"


def _resume_counts(study_dir: Path, runnable: pd.DataFrame, substudy, only_failed,
                   force, limit):
    """(already_ok, to_run) for the runnable selection given the prior manifest."""
    runnable_ids = [str(c) for c in runnable["case_id"]]
    mpath = study_dir / "run_manifest.csv"
    if mpath.exists():
        prior = pd.read_csv(mpath)
        prior = prior[prior["case_id"].astype(str).isin(set(runnable_ids))][["case_id", "status"]]
        seen = {str(c) for c in prior["case_id"]}
        missing = [cid for cid in runnable_ids if cid not in seen]
        if missing:
            prior = pd.concat([prior, pd.DataFrame({"case_id": missing, "status": "pending"})],
                              ignore_index=True)
    else:
        prior = pd.DataFrame({"case_id": runnable_ids, "status": "pending"})

    to_run = select_cases_to_run(prior, runnable, only_failed=only_failed, force=force,
                                 substudy=substudy, limit=limit)
    scope = prior
    if substudy:
        sub_ids = {str(c) for c in runnable.loc[runnable["substudy_id"] == substudy, "case_id"]}
        scope = prior[prior["case_id"].astype(str).isin(sub_ids)]
    n_ok = int((scope["status"].astype(str) == "ok").sum())
    return n_ok, len(to_run)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True)
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview counts/models/resume status; write & run nothing.")
    parser.add_argument("--only-failed", action="store_true",
                        help="Re-run only cases currently marked 'failed'.")
    parser.add_argument("--force", "--rerun-all", action="store_true", dest="force",
                        help="Re-run all selected cases, ignoring prior 'ok' status.")
    parser.add_argument("--rebuild-coefficients", action="store_true",
                        help="Refit base NASA9 coefficients and regenerate ΔG variants "
                             "(use after changing the Gibbs seed). Distinct from --force, "
                             "which only reruns cases.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Run at most N cases (benchmarking / smoke test).")
    parser.add_argument("--substudy", default=None,
                        help="Restrict execution to one substudy (design_matrix.csv stays full).")
    args = parser.parse_args(argv)

    try:
        config = load_study_config(args.config)
        species_df = load_species_for_config(config, PROJECT_ROOT)
        gibbs_seed_df = load_gibbs_seed_for_config(config, PROJECT_ROOT)
        validate_study(config, species_df, gibbs_seed_df)
    except StudyConfigError as exc:
        print(f"Config error: {exc}", file=sys.stderr)
        return 1

    study_dir = _study_dir(config)
    phase_name = config.get("base_conditions", {}).get("phase_name", "aqueous")
    solver = config.get("base_conditions", {}).get("solver", "vcs")
    max_steps = int(config.get("base_conditions", {}).get("max_steps", 100_000))
    allowed_base = [str(s) for s in config.get("model", {}).get("allowed_species", [])]

    mode_type = config.get("mode", {}).get("type", "single_product_sensitivity")
    # design_matrix.csv is ALWAYS the full study; --substudy only restricts execution.
    full_design = build_full_design_matrix(config)
    if args.substudy and args.substudy not in set(full_design["substudy_id"]):
        print(f"Config error: no cases for substudy '{args.substudy}'.", file=sys.stderr)
        return 1

    # ---- Dry-run: preview only, no writes, no run. ----
    if args.dry_run:
        coeff_df = _load_coeff_for_preview(config, study_dir)
        runnable, unmaterialized = _partition_runnable(full_design, coeff_df)
        _, models_df = compute_model_table(runnable, allowed_base, coeff_df, phase_name)
        reuse = model_reuse_stats(runnable, models_df)
        print(f"Study: {config['study']['study_id']}  (output {study_dir})")
        _print_counts(full_design, runnable, unmaterialized, models_df, reuse)
        n_ok, n_to_run = _resume_counts(study_dir, runnable, args.substudy,
                                        args.only_failed, args.force, args.limit)
        print(f"\nResume ({_mode_label(args)}): {n_ok} already ok, "
              f"{n_to_run} to run this invocation.")
        prior = study_dir / "run_manifest.csv"
        if prior.exists():
            rt = pd.read_csv(prior)["runtime_seconds"].dropna()
            if len(rt) and n_to_run:
                print(f"Est. runtime (prior median {rt.median():.3f}s/case): "
                      f"~{rt.median() * n_to_run:.0f}s for {n_to_run} cases")
        elif n_to_run:
            print("Est. runtime: no prior timing — run --limit 20 once to benchmark.")
        print("\n[dry-run] Nothing written or executed.")
        return 0

    # ---- Real run: build coefficients + models, then persist the FULL design. ----
    seed_path = PROJECT_ROOT / config.get("species_files", {}).get("gibbs_seed_wide_csv", "")
    if seed_is_stale(study_dir, seed_path) and not args.rebuild_coefficients:
        print("WARNING: the Gibbs seed file has changed since the last run — the "
              "study-local NASA9 coefficients may be stale. Re-run with "
              "--rebuild-coefficients to refit them.", file=sys.stderr)

    coeff_path = prepare_study_coefficients(config, study_dir,
                                            force=args.rebuild_coefficients)
    coeff_df = load_coefficients(coeff_path)
    offsets_df = build_thermo_offsets_table(config)
    species_meta = augment_species_metadata_with_variants(species_df, offsets_df)
    (study_dir / "processed").mkdir(parents=True, exist_ok=True)
    species_meta.to_csv(study_dir / "processed" / "species_with_variants.csv", index=False)

    runnable, unmaterialized = _partition_runnable(full_design, coeff_df)
    if runnable.empty:
        print("Nothing runnable: no target variants have coefficients.", file=sys.stderr)
        return 1

    # Manifests cover ALL runnable cases (canonical set); --substudy/--limit only
    # restrict which run. build_run_manifest merges prior statuses (resume-safe).
    design_mid, models_df, reuse = build_model_manifest(
        runnable, species_meta, coeff_df, allowed_base, study_dir, phase_name,
        model_mode=mode_type)

    # design_matrix.csv stays the FULL study; stamp the real model_id + case_hash.
    model_by_case = dict(zip(design_mid["case_id"], design_mid["model_id"]))
    full_design = full_design.copy()
    full_design["model_id"] = full_design["case_id"].map(model_by_case).fillna("")
    full_design = add_case_hash(full_design)
    write_design_outputs(full_design, config)

    run_manifest = build_run_manifest(design_mid, models_df, study_dir)
    _print_counts(full_design, runnable, unmaterialized, models_df, reuse)

    n_ok, n_to_run = _resume_counts(study_dir, runnable, args.substudy,
                                    args.only_failed, args.force, args.limit)
    print(f"\nResume ({_mode_label(args)}): {n_ok} already ok, {n_to_run} to run.")

    # A fully completed study can be inspected without Cantera, so return early
    # before the preflight import. Leave the existing run_provenance.json untouched
    # on a no-op resume (don't clobber a real run's record with cantera: null).
    if n_to_run == 0:
        print("All selected cases already ok — nothing to run (use --force to rerun).")
        return 0

    # Preflight: fail clearly if Cantera is missing rather than marking all failed.
    try:
        import cantera  # noqa: F401
    except ImportError:
        print("\nCantera is not installed in this environment. Manifests and model "
              "YAMLs were written to "
              f"{study_dir}, but the equilibrium run needs a Cantera-enabled env "
              "(conda install -c conda-forge cantera, or pip install cantera). "
              "Re-run this command there.", file=sys.stderr)
        return 2

    # Cases will run: now record provenance (captures the live Cantera version).
    write_run_provenance(study_dir, args.config, config, PROJECT_ROOT)
    scenarios = load_scenarios(study_dir / "generated_scenarios.yaml")
    run_sensitivity_manifest(
        run_manifest, scenarios, design_mid, study_dir,
        output_long_csv=study_dir / "results" / "equilibrium_raw_long.csv",
        phase_name=phase_name, solver=solver, max_steps=max_steps,
        model_mode=mode_type, only_failed=args.only_failed, limit=args.limit,
        substudy=args.substudy, force=args.force)

    final = pd.read_csv(study_dir / "run_manifest.csv")
    n_ok = int((final["status"] == "ok").sum())
    n_failed = int((final["status"] == "failed").sum())
    n_pending = int((final["status"] == "pending").sum())
    print(f"\nDone. ok={n_ok} failed={n_failed} pending={n_pending}. "
          f"Raw long: {study_dir / 'results' / 'equilibrium_raw_long.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
